services:
  - type: web
    runtime: python
    name: nnsf-app
    buildCommand: "./build.sh"
    startCommand: "gunicorn yandytech.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nnsf-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11

databases:
  - name: nnsf-db
